variables:
  NEXUS_URL: http://swarm-nexus-ingress-controller.swarm-nexus.svc.k8s.prod-dl/repository
  NEXUS_REPO: swarm-apt-hosted
  REPODIR: /builds/swarm/swarm/ndpi/ndpi-netfilter/
  NDPI_VER: "4.9"
  IMAGE: harbor.wildberries.ru/swarm/swarm/swarmops/docker-factory/deb-builder
  TAG: v0-0-9-1c7e6296

stages:
  - build
  - push-nexus


default:
  image:
    name: $IMAGE:$TAG
  before_script:
    - export PREFIX="${PREFIX#v}"
  artifacts:
    paths:
      - "$REPODIR/*.deb"
    expire_in: 1 hour
  tags:
    - swarm

dkms:
  stage: build
  script:
    - apt-get install -y linux-headers-$(uname -r) autoconf automake autogen libpcap-dev libtool libgcrypt20-dev
    - ./autogen.sh
    - ./configure '--with-ndpi-netfilter'
    - sed -i ./ndpi-netfilter/dkms/dkms.conf -e "s/4.9/$PREFIX/"
    - sed -i ./ndpi-netfilter/dkms/Makefile -e "s/4.9/$PREFIX/"
    - make -C src/lib
    - make dkms
    - make dkms_deb
    - mv /var/lib/dkms/xt_ndpi/${PREFIX}/deb/* $REPODIR
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^feature-.*-\d{1,9}$/ || $CI_COMMIT_BRANCH =~ /^fix-.*-\d{1,9}$/
      variables:
        PREFIX: $NDPI_VER-$CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        PREFIX: $NDPI_VER-$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+/
      variables:
        PREFIX: $CI_COMMIT_TAG

push:
  stage: push-nexus
  dependencies:
    - dkms
  script:
    - ls -lah
    - 'curl -X POST -u "$USER:$PASSWORD" -H "Content-Type: multipart/form-data; charset=utf-8" --data-binary "@xt-ndpi-dkms_${PREFIX}_amd64.deb" "$NEXUS_URL/$NEXUS_REPO/"'
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+/
      variables:
        PREFIX: $CI_COMMIT_TAG
  variables:
    GIT_STRATEGY: none
