include:
  - project: 'swarm/swarmops/devops/ci/ci-templates'
    ref: v1.1.0
    file: '/nexus/package.yml'

stages:
  - build package
  - deploy package
  - check approve

variables:
  PACKAGE_TYPE: deb
  REPODIR: /builds/swarm/swarm/ndpi/
  NDPI_VER: "4.9"

build:
  stage: build package
  before_script:
    - export PREFIX="${PREFIX#v}"
  script:
    - apt-get install -y linux-headers-$(uname -r) autoconf automake autogen libpcap-dev libtool libgcrypt20-dev
    - ./autogen.sh
    - ./configure '--with-ndpi-netfilter'
    - sed -i ./ndpi-netfilter/dkms/dkms.conf -e "s/4.9/$PREFIX/"
    - sed -i ./ndpi-netfilter/dkms/Makefile -e "s/4.9/$PREFIX/"
    - make -C src/lib
    - make dkms
    - make dkms_deb
    - mv /var/lib/dkms/xt_ndpi/${PREFIX}/deb/* $REPODIR
  tags:
    - swarm
  rules:
    - if: "$CI_COMMIT_TAG =~ /^v([0-9]+)\\.([0-9]+)\\.([0-9]+)-?([a-zA-Z0-9\\.]*)\\+?([a-zA-Z0-9\\.]*)$/"
      variables:
        PREFIX: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^(feature|fix)-[a-z]+-\d+$/
      variables:
        PREFIX: $NDPI_VER-$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME-$CI_COMMIT_SHORT_SHA
