include:
  - project: 'swarm/swarmops/devops/ci/ci-templates'
    ref: v1.1.0
    file: '/nexus/package.yml'

stages:
  - build package
  - deploy package
  - check approve

variables:
  PACKAGE_TYPE: deb
  REPODIR: /builds/swarm/swarm/ndpi/
  NDPI_VER: "4.9"

build:
  stage: build package
  before_script:
    - |+
      if [ -z ${CI_COMMIT_TAG+x} ]; then export STRIPPED_VERSION=$NDPI_VER-$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME-$CI_COMMIT_SHORT_SHA; else export STRIPPED_VERSION="${CI_COMMIT_TAG#v}"; fi
  script:
    - apt-get install -y linux-headers-$(uname -r) autoconf automake autogen libpcap-dev libtool libgcrypt20-dev
    - ./autogen.sh
    - ./configure '--with-ndpi-netfilter'
    - sed -i ./ndpi-netfilter/dkms/dkms.conf -e "s/4.9/$STRIPPED_VERSION/"
    - sed -i ./ndpi-netfilter/dkms/Makefile -e "s/4.9/$STRIPPED_VERSION/"
    - make -C src/lib
    - make dkms
    - make dkms_deb
    - mv /var/lib/dkms/xt_ndpi/${STRIPPED_VERSION}/deb/* $REPODIR
  tags:
    - swarm
